### PR TITLE
rnmd notebook dir; added model_tuner version print to scripts

### PR DESCRIPTION
**Pull request by lshpaner**
- Renamed `notebooks` directory to `py_scripts`  $\longrightarrow$ kept existing `.py` scripts there; moved `.ipynb` to `notebooks` folder. 
- Added version and author information about `model_tuner` to each script s/t there exists full transparency on which version is running at any given time
- Added appropriate class labels for Iris dataset in `multi_class_test.py`

### CODE REVIEW

**Comment by panas89** [comment]
maybe we should rename the py_scripts to py_test_scripts or py_example_scripts

**Comment by panas89** [comment]
everything looks great I can test all the files except the ones using ucirepo for some reason cannot connect to their server

also what is this file notebooks/=1.0.0?

**Comment by lshpaner** [comment]
> everything looks great I can test all the files except the ones using ucirepo for some reason cannot connect to their server
> 
> also what is this file notebooks/=1.0.0?

- UCI ML repo is known to have recurring connection/server issues from time to time, though rare. It should fix itself within the hour or day.
- the `1.0.0` is a catboost or some other artifact left over unintentionally in the notebooks dir. We can safely remove it.

**Comment by panas89** [comment]
I dont think the following notebook code works anymore, notebooks/binary_test.ipynb

**Comment by lshpaner** [comment]
> I dont think the following notebook code works anymore, notebooks/binary_test.ipynb

I don't see any benefit from keeping it, since we already have plenty of similar (if not identical) py scripts as well as updated notebook examples on colab.

**Pull request merged**
